/// x1zz-compiler/src/emitter.rs — Rust 코드 에밋 (Transpiler Layer) v2
///
/// .xzz 스크립트 → 독립 실행 가능한 Rust + Polars 소스 코드 생성기.
///
/// 변환 규칙 (syntax.md / architecture.md 준수):
///   load("path") :: Schema  →  load_csv("path")?.lazy()
///   |> filter(<expr>)       →  .filter(<polars expr>)  [타입 인식 리터럴]
///   |> select([cols])       →  .select([col("a"), ...])  [스키마 검증]
///   |> count                →  df.height() 로 행 수 확인
///   마지막에 .collect()?    →  LazyFrame → DataFrame (Eager 실행)
///
/// [v2 변경사항]
///   - 스키마 기반 컬럼명 검증:
///       TypeDecl에 선언되지 않은 컬럼을 filter/select에 사용하면
///       emit 단계에서 [SchemaError] Result::Err 를 반환한다.
///   - 타입 인식 리터럴 생성:
///       float / Option<float> 컬럼과 비교 시 IntLit → lit(Xf64) 자동 변환.
///       Polars 타입 불일치 컴파일 에러 사전 방지.
///   - 편집 거리 기반 오타 힌트:
///       → Did you mean: col("pm10")  (Levenshtein 거리 최솟값)

use std::collections::HashMap;
use std::fs;

use crate::ast::{BinOpKind, Expr, PipelineOp, PipelineSource, Program, Stmt};
use crate::{Codegen, Lexer, Parser, StructField};

// ─────────────────────────────────────────────────────────────────────────────
// ── 공개 진입점 ───────────────────────────────────────────────────────────────
// ─────────────────────────────────────────────────────────────────────────────

/// .xzz 파일을 독립 실행 가능한 Rust 소스 코드로 변환한다.
///
/// # 에러
/// - IO 에러 (파일 없음 / 쓰기 실패)
/// - 렉서 에러 / 파서 에러
/// - `[SchemaError]`: 선언되지 않은 컬럼을 filter/select에 사용한 경우
pub fn emit_rust(
    source_path: &str,
    out_path: Option<&str>,
) -> Result<(), Box<dyn std::error::Error>> {
    // ── Step 1: 소스 파일 읽기 ───────────────────────────────────────────────
    let source = fs::read_to_string(source_path)
        .map_err(|e| format!("IO 에러: 파일 읽기 실패 '{}' — {}", source_path, e))?;

    // ── Step 2: 렉서 ────────────────────────────────────────────────────────
    let mut lexer = Lexer::new(&source);
    let tokens = lexer.tokenize().map_err(|e| format!("{}", e))?;

    // ── Step 3: 파서 ────────────────────────────────────────────────────────
    let mut parser = Parser::new(tokens);
    let program = parser.parse().map_err(|e| format!("{}", e))?;

    // ── Step 4: 스키마 검증 + Rust 코드 생성 (에러 → Result::Err 반환) ───────
    let rust_code = generate_rust_src(&program, source_path)?;

    // ── Step 5: 출력 ────────────────────────────────────────────────────────
    match out_path {
        Some(path) => {
            fs::write(path, &rust_code)
                .map_err(|e| format!("IO 에러: 출력 파일 쓰기 실패 '{}' — {}", path, e))?;

            println!("✅  emit rust 완료 → {}", path);
            println!();
            println!("─── 실행 방법 ──────────────────────────────────────────────────");
            println!("  1) 새 Rust 프로젝트 생성:");
            println!("       cargo new my_analysis && cd my_analysis");
            println!("  2) Cargo.toml 에 의존성 추가:");
            println!("       polars      = {{ version = \"0.53\", features = [\"lazy\", \"csv\"] }}");
            println!("       encoding_rs = \"0.8\"");
            println!("  3) {} 를 src/main.rs 로 복사 후 실행:", path);
            println!("       cargo run");
            println!("────────────────────────────────────────────────────────────────");
        }
        None => println!("{}", rust_code),
    }

    Ok(())
}

// ─────────────────────────────────────────────────────────────────────────────
// ── 내부: AST → Rust 소스 문자열 생성 ─────────────────────────────────────────
// ─────────────────────────────────────────────────────────────────────────────

/// Program AST를 독립 실행 가능한 Rust fn main() 소스 문자열로 변환한다.
/// 스키마 검증 오류 시 `[SchemaError]` 형식의 에러를 반환한다.
fn generate_rust_src(
    program: &Program,
    source_path: &str,
) -> Result<String, Box<dyn std::error::Error>> {
    // ── 전역 스키마 맵 구축: type_name → Vec<StructField> ────────────────────
    let mut schema_map: HashMap<String, Vec<StructField>> = HashMap::new();
    for stmt in &program.stmts {
        if let Stmt::TypeDecl { name, fields } = stmt {
            schema_map.insert(name.clone(), fields.clone());
        }
    }

    let mut out = String::new();

    // 파일 헤더
    out.push_str("// ═══════════════════════════════════════════════════════════════\n");
    out.push_str("// Auto-generated by x1zzLang `emit rust`\n");
    out.push_str(&format!("// Source: {}\n", source_path));
    out.push_str("//\n");
    out.push_str("// [필요한 Cargo.toml 의존성]\n");
    out.push_str("//   polars      = { version = \"0.53\", features = [\"lazy\", \"csv\"] }\n");
    out.push_str("//   encoding_rs = \"0.8\"\n");
    out.push_str("// ═══════════════════════════════════════════════════════════════\n\n");

    // 임포트
    out.push_str("use polars::prelude::*;\n");
    out.push_str("use encoding_rs::EUC_KR;\n");
    out.push_str("use std::io::Cursor;\n\n");

    // CSV 로더 헬퍼
    out.push_str(&emit_csv_loader_fn());
    out.push('\n');

    // fn main()
    out.push_str("fn main() -> Result<(), Box<dyn std::error::Error>> {\n");

    // TypeDecl → 스키마 주석 블록
    let has_schemas = program
        .stmts
        .iter()
        .any(|s| matches!(s, Stmt::TypeDecl { .. }));
    if has_schemas {
        out.push_str(
            "    // ── x1zzLang Schema Definitions (참조용 주석) ─────────────────────\n",
        );
        for stmt in &program.stmts {
            if let Stmt::TypeDecl { name, fields } = stmt {
                out.push_str(&format!("    // type {} = {{\n", name));
                for f in fields {
                    out.push_str(&format!("    //   {:<14}: {}\n", f.name, f.field_type));
                }
                out.push_str("    // }\n");
            }
        }
        out.push_str(
            "    // ──────────────────────────────────────────────────────────────────\n\n",
        );
    }

    // 변수별 스키마 추적 (VarRef 체이닝 지원)
    // var_name → HashMap<col_name, type_string>
    let mut var_col_types: HashMap<String, HashMap<String, String>> = HashMap::new();

    // VarDecl → LazyFrame 파이프라인
    for stmt in &program.stmts {
        if let Stmt::VarDecl {
            var_name,
            is_mut,
            source,
            ops,
        } = stmt
        {
            let mut_kw = if *is_mut { "mut " } else { "" };

            // ── 이 VarDecl의 활성 컬럼 타입 맵 결정 ─────────────────────────
            // Load: globally declared schema → col_types
            // VarRef: propagated from source variable
            let col_types: HashMap<String, String> = match source {
                PipelineSource::Load { schema_name, .. } => schema_map
                    .get(schema_name)
                    .map(|fields| {
                        fields
                            .iter()
                            .map(|f| (f.name.clone(), f.field_type.clone()))
                            .collect()
                    })
                    .unwrap_or_default(),

                PipelineSource::VarRef(src_var) => var_col_types
                    .get(src_var.as_str())
                    .cloned()
                    .unwrap_or_default(),
            };

            // ── 스키마 검증: filter/select 내 모든 컬럼 참조 확인 ─────────────
            // col_types가 비어 있으면(스키마 미선언) 검증 생략
            if !col_types.is_empty() {
                for op in ops {
                    validate_op_columns(op, &col_types, source_path)?;
                }
            }

            // ── 코드 생성 ────────────────────────────────────────────────────
            out.push_str(&format!(
                "    // ── Pipeline: {}v {} ────────────────────────────────────────────\n",
                mut_kw, var_name
            ));

            // 소스 결정
            match source {
                PipelineSource::Load {
                    file_path,
                    schema_name,
                } => {
                    out.push_str(&format!(
                        "    // load(\"{}\") :: {}\n",
                        file_path, schema_name
                    ));
                    out.push_str(&format!(
                        "    let {}{} = load_csv(\"{}\")? // :: {}\n",
                        mut_kw, var_name, file_path, schema_name
                    ));
                    out.push_str("        .lazy()\n");
                }
                PipelineSource::VarRef(src_var) => {
                    out.push_str(&format!(
                        "    let {}{} = {}.clone().lazy()\n",
                        mut_kw, var_name, src_var
                    ));
                }
            }

            // 파이프라인 연산자 체이닝
            let mut has_count = false;
            for op in ops {
                match op {
                    PipelineOp::Filter(expr) => {
                        // 타입 인식 Polars 표현식 생성
                        let polars_expr = to_typed_polars_expr(expr, &col_types);
                        out.push_str(&format!(
                            "        .filter({})  // |> filter({})\n",
                            polars_expr,
                            Codegen::expr_to_xzz(expr)
                        ));
                    }
                    PipelineOp::Select(cols) => {
                        let polars_cols: Vec<String> =
                            cols.iter().map(|c| format!("col(\"{}\")", c)).collect();
                        out.push_str(&format!(
                            "        .select([{}])  // |> select([{}])\n",
                            polars_cols.join(", "),
                            cols.join(", ")
                        ));
                    }
                    PipelineOp::Count => {
                        has_count = true;
                    }
                }
            }

            // collect
            out.push_str("        .collect()?;\n");

            // 결과 출력
            if has_count {
                out.push_str(&format!(
                    "    println!(\"[{}] count = {{}}\", {}.height());\n",
                    var_name, var_name
                ));
            } else {
                out.push_str(&format!(
                    "    println!(\"[{}]\\n{{}}\", {});\n",
                    var_name, var_name
                ));
            }
            out.push('\n');

            // 이 변수의 컬럼 타입 맵 저장 (다음 VarRef에서 참조 가능)
            if !col_types.is_empty() {
                var_col_types.insert(var_name.clone(), col_types);
            }
        }
    }

    out.push_str("    Ok(())\n");
    out.push_str("}\n");

    Ok(out)
}

// ─────────────────────────────────────────────────────────────────────────────
// ── 스키마 기반 컬럼명 검증 ────────────────────────────────────────────────────
// ─────────────────────────────────────────────────────────────────────────────

/// PipelineOp 내의 모든 컬럼 참조를 col_types 맵으로 검증한다.
///
/// 미선언 컬럼 발견 시 error_standards.md 형식의 [SchemaError] Err 반환.
fn validate_op_columns(
    op: &PipelineOp,
    col_types: &HashMap<String, String>,
    source_path: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    match op {
        PipelineOp::Filter(expr) => {
            // filter 조건 내의 Ident(컬럼 참조)를 재귀 검증
            validate_expr_columns(expr, col_types, source_path)?;
        }
        PipelineOp::Select(cols) => {
            // select 목록의 각 컬럼명 검증
            for col_name in cols {
                if !col_types.contains_key(col_name.as_str()) {
                    let available: Vec<&str> =
                        col_types.keys().map(String::as_str).collect();
                    let suggestion =
                        find_closest_col(col_name, &available).unwrap_or(col_name);
                    return Err(format!(
                        "[SchemaError] at {}\n\
                         ─────────────────────────────────────────────\n\
                         Cause   : select() 에 선언되지 않은 컬럼이 있습니다.\n\
                         Detail  : column '{}' not found in schema\n\
                         Available: {}\n\
                         → Did you mean: col(\"{}\")",
                        source_path,
                        col_name,
                        available.join(", "),
                        suggestion
                    )
                    .into());
                }
            }
        }
        PipelineOp::Count => {}
    }
    Ok(())
}

/// 표현식 내의 Ident(컬럼 참조)를 재귀적으로 검증한다.
fn validate_expr_columns(
    expr: &Expr,
    col_types: &HashMap<String, String>,
    source_path: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    match expr {
        Expr::Ident(col_name) => {
            if !col_types.contains_key(col_name.as_str()) {
                let available: Vec<&str> = col_types.keys().map(String::as_str).collect();
                let suggestion =
                    find_closest_col(col_name, &available).unwrap_or(col_name);
                return Err(format!(
                    "[SchemaError] at {}\n\
                     ─────────────────────────────────────────────\n\
                     Cause   : filter() 에 선언되지 않은 컬럼이 있습니다.\n\
                     Detail  : column '{}' not found in schema\n\
                     Available: {}\n\
                     → Did you mean: col(\"{}\")",
                    source_path,
                    col_name,
                    available.join(", "),
                    suggestion
                )
                .into());
            }
            Ok(())
        }
        Expr::BinOp { lhs, rhs, .. } => {
            // lhs: 보통 컬럼 Ident → 검증
            validate_expr_columns(lhs, col_types, source_path)?;
            // rhs: 보통 리터럴이지만, 컬럼-컬럼 비교인 경우 함께 검증
            if matches!(rhs.as_ref(), Expr::Ident(_)) {
                validate_expr_columns(rhs, col_types, source_path)?;
            }
            Ok(())
        }
        _ => Ok(()),
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// ── 타입 인식 Polars 표현식 생성 ──────────────────────────────────────────────
// ─────────────────────────────────────────────────────────────────────────────

/// AST Expr → Polars Rust 코드 문자열 (컬럼 타입 인식 리터럴 포함).
///
/// float / Option<float> 컬럼과 비교하는 경우 IntLit을 `lit(Xf64)` 로 변환해
/// Polars 0.53 에서 발생하는 타입 불일치 컴파일 에러를 방지한다.
fn to_typed_polars_expr(expr: &Expr, col_types: &HashMap<String, String>) -> String {
    match expr {
        Expr::Ident(s) => format!("col(\"{}\")", s),
        Expr::StringLit(s) => format!("lit(\"{}\")", s),
        Expr::IntLit(n) => format!("lit({}i64)", n),
        Expr::FloatLit(f) => format!("lit({}f64)", f),
        Expr::BinOp { lhs, op, rhs } => {
            // lhs 컬럼 타입이 float 계열인지 판별
            let lhs_is_float = if let Expr::Ident(col_name) = lhs.as_ref() {
                col_types
                    .get(col_name.as_str())
                    .map(|t| t.contains("float"))
                    .unwrap_or(false)
            } else {
                false
            };

            let l = to_typed_polars_expr(lhs, col_types);

            // lhs가 float 컬럼이면 rhs IntLit → f64 리터럴로 변환
            let r = if lhs_is_float {
                match rhs.as_ref() {
                    Expr::IntLit(n) => format!("lit({:.1}f64)", *n as f64),
                    Expr::FloatLit(f) => format!("lit({}f64)", f),
                    other => to_typed_polars_expr(other, col_types),
                }
            } else {
                to_typed_polars_expr(rhs, col_types)
            };

            let op_method = match op {
                BinOpKind::Eq    => "eq",
                BinOpKind::NotEq => "neq",
                BinOpKind::Lt    => "lt",
                BinOpKind::Gt    => "gt",
                BinOpKind::LtEq  => "lt_eq",
                BinOpKind::GtEq  => "gt_eq",
            };
            format!("{}.{}({})", l, op_method, r)
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// ── 오타 힌트: 편집 거리 기반 컬럼명 제안 ───────────────────────────────────────
// ─────────────────────────────────────────────────────────────────────────────

/// Levenshtein 편집 거리가 가장 작은 유효 컬럼명을 반환한다.
/// SchemaError의 `Did you mean:` 힌트에 사용한다.
fn find_closest_col<'a>(name: &str, candidates: &[&'a str]) -> Option<&'a str> {
    candidates
        .iter()
        .min_by_key(|&&c| edit_distance(name, c))
        .copied()
}

/// Levenshtein 편집 거리 계산
fn edit_distance(a: &str, b: &str) -> usize {
    let a: Vec<char> = a.chars().collect();
    let b: Vec<char> = b.chars().collect();
    let (m, n) = (a.len(), b.len());
    let mut dp = vec![vec![0usize; n + 1]; m + 1];
    for i in 0..=m {
        dp[i][0] = i;
    }
    for j in 0..=n {
        dp[0][j] = j;
    }
    for i in 1..=m {
        for j in 1..=n {
            dp[i][j] = if a[i - 1] == b[j - 1] {
                dp[i - 1][j - 1]
            } else {
                1 + dp[i - 1][j].min(dp[i][j - 1]).min(dp[i - 1][j - 1])
            };
        }
    }
    dp[m][n]
}

// ─────────────────────────────────────────────────────────────────────────────
// ── 생성된 파일에 포함될 CSV 로더 헬퍼 함수 소스 ──────────────────────────────
// ─────────────────────────────────────────────────────────────────────────────

/// EUC-KR(CP949) 자동 감지 CSV 로더 함수 소스 문자열.
/// 생성된 Rust 파일에 인라인으로 삽입되어 독립 실행을 가능하게 한다.
fn emit_csv_loader_fn() -> String {
    r#"/// EUC-KR(CP949) 자동 감지 CSV 로더
/// UTF-8 직접 시도 → 실패 시 EUC-KR 디코딩 (한국 공공데이터 대응)
fn load_csv(file_path: &str) -> Result<DataFrame, Box<dyn std::error::Error>> {
    let raw_bytes = std::fs::read(file_path)?;

    // UTF-8 직접 시도 → 실패 시 EUC-KR(CP949) 디코딩
    let utf8_string = match String::from_utf8(raw_bytes.clone()) {
        Ok(s) => s,
        Err(_) => {
            let (cow, _, _) = EUC_KR.decode(&raw_bytes);
            cow.into_owned()
        }
    };

    let cursor = Cursor::new(utf8_string.into_bytes());
    let df = CsvReadOptions::default()
        .with_infer_schema_length(Some(200))
        .with_parse_options(
            CsvParseOptions::default()
                .with_null_values(Some(NullValues::AllColumnsSingle("-".into()))),
        )
        .into_reader_with_file_handle(cursor)
        .finish()?;

    Ok(df)
}
"#
    .to_string()
}
