/**
 * x1zzTranspiler.js
 * 캔버스의 노드 DAG를 x1zzLang 코드 문자열로 변환하는 핵심 엔진
 */

import { findRootNodes, topologicalSort } from './dagWalker.js';
import { NODE_MAPPINGS, getFallbackMapping } from './nodeMappings.js';

/**
 * 변수 이름 생성 헬퍼: 노드 라벨과 ID를 조합하여 유효한 식별자 반환
 * @param {Object} node
 * @param {number} index
 * @returns {string}
 */
function makeVarName(node, index) {
  const label = node.data?.label || node.type || 'data';
  // 알파벳/숫자/_만 남기고, 앞에 숫자가 오면 prefix 추가
  const sanitized = label
    .replace(/[^a-zA-Z0-9_]/g, '_')
    .replace(/^(\d)/, '_$1')
    .toLowerCase();
  return sanitized || `var_${index}`;
}

/**
 * 안전한 식별자로 중복 없이 이름을 생성합니다.
 * @param {string} base
 * @param {Set} usedNames
 * @returns {string}
 */
function uniqueName(base, usedNames) {
  let name = base;
  let counter = 2;
  while (usedNames.has(name)) {
    name = `${base}_${counter++}`;
  }
  usedNames.add(name);
  return name;
}

/**
 * 메인 변환 함수: nodes + edges 배열을 받아 x1zzLang 소스코드 문자열을 반환합니다.
 *
 * 변환 전략:
 * 1. DAG를 위상 정렬하여 실행 순서를 결정합니다.
 * 2. fileInput 노드에서 시작하는 각 파이프라인 체인을 탐색합니다.
 * 3. 각 노드를 nodeMappings 규칙에 따라 x1zzLang 구문으로 변환합니다.
 * 4. 최종 코드 문자열을 반환합니다.
 *
 * @param {Array} nodes - React Flow 노드 배열
 * @param {Array} edges - React Flow 엣지 배열
 * @returns {string} x1zzLang 소스 코드
 */
export function transpileToX1zz(nodes, edges) {
  // 주석/컨테이너 노드 제외
  const validNodes = nodes.filter(n => n.type !== 'comment' && n.type !== 'container');
  const validEdges = edges.filter(e => {
    const srcExists = validNodes.some(n => n.id === e.source);
    const tgtExists = validNodes.some(n => n.id === e.target);
    return srcExists && tgtExists;
  });

  if (validNodes.length === 0) {
    return '// No nodes found in the canvas.\n';
  }

  // 위상 정렬
  const sortedNodes = topologicalSort(validNodes, validEdges);

  // 노드 ID → 변수 이름 맵
  const nodeVarMap = new Map();
  const usedNames = new Set();

  sortedNodes.forEach((node, idx) => {
    const base = makeVarName(node, idx);
    const varName = uniqueName(base, usedNames);
    nodeVarMap.set(node.id, varName);
  });

  // 헤더 주석 생성
  const lines = [];
  lines.push('// ============================================');
  lines.push('// Generated by x1zzLang Visual IDE Transpiler');
  lines.push(`// Nodes: ${validNodes.length}  |  Edges: ${validEdges.length}`);
  lines.push(`// Generated at: ${new Date().toISOString()}`);
  lines.push('// ============================================');
  lines.push('');

  // 파이프라인 체인별로 코드 생성
  // fileInput 루트 노드를 찾아 각각의 체인을 생성
  const rootNodes = findRootNodes(validNodes, validEdges);

  if (rootNodes.length === 0) {
    lines.push('// WARNING: No root (source) nodes found. Check for cycles or disconnected nodes.');
    lines.push('');
  }

  // 이미 처리한 노드 추적 (여러 체인에서 공유 노드 중복 방지)
  const processedNodeIds = new Set();

  // 각 루트 노드에서 시작하는 파이프라인 작성
  rootNodes.forEach((rootNode, chainIdx) => {
    if (processedNodeIds.has(rootNode.id)) return;

    const chainVarName = nodeVarMap.get(rootNode.id) || `pipeline_${chainIdx + 1}`;

    lines.push(`// --- Pipeline Chain ${chainIdx + 1}: ${rootNode.data?.label || rootNode.type} ---`);
    lines.push('');

    // BFS로 이 루트에서 연결된 노드들을 순서대로 수집
    const chainNodes = collectChain(rootNode.id, sortedNodes, validEdges);

    // 체인의 소스 노드(fileInput 등)를 먼저 처리
    let currentPipelineVar = null;
    const pipelineLines = [];

    // 체인 내 공유 columnMapping (source 노드에서 downstream으로 전파)
    let chainColumnMapping = {};

    chainNodes.forEach(node => {
      if (processedNodeIds.has(node.id)) return;
      processedNodeIds.add(node.id);

      const varName = nodeVarMap.get(node.id) || node.id;
      const mapper = NODE_MAPPINGS[node.type] || null;

      // 업스트림 변수 목록 (join, union 등 다중 입력을 위해)
      const upstreamEdges = validEdges.filter(e => e.target === node.id);
      const upstreamVarNames = upstreamEdges.map(e => nodeVarMap.get(e.source)).filter(Boolean);

      // source 노드에서 생성된 columnMapping을 downstream 노드에 전파
      if (node.type !== 'fileInput' && Object.keys(chainColumnMapping).length > 0) {
        if (!node.data) node.data = {};
        if (!node.data.parameters) node.data.parameters = {};
        // 이미 자체 mapping이 없을 때만 체인 mapping 적용
        if (!node.data.parameters.columnMapping) {
          node.data.parameters.columnMapping = chainColumnMapping;
        }
      }

      const result = mapper
        ? mapper(node, varName, upstreamVarNames)
        : getFallbackMapping(node);

      if (result.type === 'source') {
        // fileInput 등 소스 노드 → 타입 블록 + load 구문
        result.lines.forEach(l => lines.push(l));
        lines.push('');
        currentPipelineVar = varName;
        // source 노드의 columnMapping을 체인 전체에 전파
        if (result.columnMapping) {
          chainColumnMapping = result.columnMapping;
        }
      } else if (result.type === 'pipeline') {
        // 파이프라인 스텝 → 들여쓰기하여 누적
        result.lines.forEach(l => pipelineLines.push('  ' + l));
      } else if (result.type === 'terminal') {
        // fileOutput 등 최종 노드 → 파이프라인 끝에 붙임
        result.lines.forEach(l => pipelineLines.push('  ' + l));
      }
    });

    // 파이프라인 스텝들이 있으면 하나의 파이프라인 표현식으로 묶기
    if (pipelineLines.length > 0 && currentPipelineVar) {
      lines.push(`v result_${chainVarName} = ${currentPipelineVar}`);
      pipelineLines.forEach(pl => lines.push(pl));
      lines.push('');
    } else if (pipelineLines.length > 0) {
      // 소스 노드 없이 파이프라인만 있는 경우 (비정상 그래프)
      lines.push(`// WARNING: Pipeline steps found without a source node`);
      pipelineLines.forEach(pl => lines.push(pl));
      lines.push('');
    }
  });

  // 연결되지 않은 고립 노드 처리
  const isolatedNodes = validNodes.filter(
    n => !processedNodeIds.has(n.id)
  );

  if (isolatedNodes.length > 0) {
    lines.push('// --- Isolated (Unconnected) Nodes ---');
    isolatedNodes.forEach(node => {
      const varName = nodeVarMap.get(node.id) || node.id;
      const mapper = NODE_MAPPINGS[node.type] || null;
      const result = mapper
        ? mapper(node, varName, [])
        : getFallbackMapping(node);

      if (result.type === 'source') {
        result.lines.forEach(l => lines.push(l));
        lines.push('');
      } else {
        lines.push(`// [isolated] ${node.data?.label || node.type}`);
        result.lines.forEach(l => lines.push('// ' + l));
        lines.push('');
      }
    });
  }

  return lines.join('\n');
}

/**
 * 특정 루트 노드에서 시작하는 체인을 위상 정렬된 순서로 반환합니다.
 * @param {string} rootId
 * @param {Array} sortedNodes - 이미 위상 정렬된 전체 노드 배열
 * @param {Array} edges
 * @returns {Array}
 */
function collectChain(rootId, sortedNodes, edges) {
  // BFS로 rootId에서 도달 가능한 모든 노드 ID 수집
  const reachable = new Set();
  const queue = [rootId];

  while (queue.length > 0) {
    const current = queue.shift();
    if (reachable.has(current)) continue;
    reachable.add(current);
    edges.filter(e => e.source === current).forEach(e => {
      if (!reachable.has(e.target)) queue.push(e.target);
    });
  }

  // 위상 정렬 순서를 유지하면서 도달 가능한 노드만 반환
  return sortedNodes.filter(n => reachable.has(n.id));
}
